[package]
name = "lines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lines_logic"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = "0.13.2"
bevy_prototype_lyon = "0.11.0"
rand = "0.8.5"
petgraph = "0.6.5"
pyo3 = { version = "0.20", features = ["extension-module"] }
